import {Food} from '../interfaces';

export const catFoods: Food[] = [
  {
    name: 'Katzenmilch',
    effectHunger: -2,
    effectThirst: -30,
    symbol: '🥛',
    effectPooLvl: 0,
    effectPeeLvl: 15,
    effectIllness: 0,
    effectTrust: 5,
    sound: null,
  },
  {
    name: 'Fisch',
    effectHunger: -2,
    effectThirst: 2,
    symbol: '🐟',
    effectPooLvl: 1,
    effectPeeLvl: 0,
    effectIllness: 0,
    effectTrust: 0,
    sound: null,
  },
  {
    name: 'Nassfutter',
    effectHunger: -45,
    effectThirst: -15,
    symbol: '🥫',
    effectPooLvl: 10,
    effectPeeLvl: 3,
    effectIllness: 2,
    effectTrust: 3,
    sound: null,
  },
  {
    name: 'Trockenfutter',
    effectHunger: -30,
    effectThirst: 15,
    symbol: '🧆',
    effectPooLvl: 5,
    effectPeeLvl: 0,
    effectIllness: 3,
    effectTrust: 2,
    sound: null,
  },
  {
    name: 'Obst',
    effectHunger: -15,
    effectThirst: -5,
    symbol: '🍎',
    effectPooLvl: 4,
    effectPeeLvl: 1,
    effectIllness: -2,
    effectTrust: 1,
    sound: null,
  },
  {
    name: 'Gemüse',
    effectHunger: -20,
    effectThirst: -5,
    symbol: '🥦',
    effectPooLvl: -2,
    effectPeeLvl: 1,
    effectIllness: -3,
    effectTrust: 2,
    sound: null,
  },
  {
    name: 'Leckerli',
    effectHunger: -1,
    effectThirst: 1,
    symbol: '🍪',
    effectPooLvl: 1,
    effectPeeLvl: 0,
    effectIllness: 2,
    effectTrust: 5,
    sound: null,
  }
];
